#pragma once
#include <stdint.h>

enum class msg_type {BOOLEAN, UPDATECONTROLLER, DOUBLE, EMPTY, FLOAT, FLOATARRAY, IMU, INFO, INT8, INTEGER, optitrack, 
                     POINTS, POSE, POSES, RESTNORMREF_SETTINGS, TAGGEDPOSES, VECTOR2D, VECTOR3D, VECTOR, VECTORDOUBLE};
